name: Collect Coverage

on:
  push:
    branches:
      - master

jobs:
  collect-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm ci

      - name: Run Tests
        run: |
          npm run test:cov

      - name: Collect Coverage
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
